# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c52b40ef6f4a135d513c37552317883a"
name = "web"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_orders,write_orders,read_customers"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "disputes/create" ]
  uri = "/webhooks/disputes-create"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
